# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
"-Zshare-generics=off",
    "-Znext-solver=coherence"
]

[target.wasm32-unknown-unknown]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
    "-Zshare-generics=off",
    "-Znext-solver=coherence"
]

[alias]
ci = "run --package ci --"

[build]
#target = "wasm32-unknown-unknown"