[package]
name = "server_dedicated_test"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
networkinator = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
message_pro_macro = { workspace = true }
replicateinator = { path = "../../../replicateinator" }
replication_pro_macro = { path = "../../../replication_pro_macro" }
